### PR TITLE
Updated Gradle wrapper to latest version 4.6

### PR DESCRIPTION
**Pull request by SimonScholz**
Change-Id: I7da4f6456d575095c88752d81313656d1a981f41
Signed-off-by: Simon Scholz <simon.scholz@vogella.com>

### CODE REVIEW

**Comment by SimonScholz** [comment]
Hi,

do you have any concerns with this patch? I'd rather use the latest gradle wrapper and therefore have the latest gradle api so that I can try to get rid of the optional dependencies issue.

See https://docs.gradle.org/4.6/release-notes.html#support-for-optional-dependencies-in-pom-consumption

**Comment by stempler** [comment]
Looks good to me. Can you please update the version to 1.7.0-SNAPSHOT in the PR? The current snapshot has been around for a while and I want to avoid any trouble from updating the Gradle version for users that use the snapshot.

**Comment by SimonScholz** [comment]
Alright done that and next up I'll investigate on the optional dependencies issue: https://docs.gradle.org/4.6/release-notes.html#support-for-optional-dependencies-in-pom-consumption

**Comment by stempler** [comment]
Thanks a lot! Looking forward to the optional dependencies feature.

**Pull request merged**
